/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.BCrypt;
import Controller.UserController;
import Dao.NguoiDungDao;
import Model.NguoiDung;
import javax.swing.JOptionPane;

/**
 *
 * @author TieuSoi
 */
public class ChangeMatKhau extends javax.swing.JDialog {

        /**
         * Creates new form ChangeMatKhau
         */
        private NguoiDung accCur;

        public NguoiDung getAccCur() {
                return accCur;
        }

        public void setAccCur(NguoiDung accCur) {
                this.accCur = accCur;
        }

        public ChangeMatKhau(javax.swing.JFrame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                setLocationRelativeTo(null);
        }

        public ChangeMatKhau(javax.swing.JFrame parent, boolean modal, NguoiDung t) {
                super(parent, modal);
                initComponents();
                setLocationRelativeTo(null);
                this.accCur = t;
                tenTaiKhoan.setText(this.accCur.getTenDangNhap());
                email.setText(this.accCur.getEmail());
        }

        ChangeMatKhau() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                               // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel3 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                panel = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                tenTaiKhoan = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                email = new javax.swing.JTextField();
                jButton1 = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                password = new javax.swing.JPasswordField();
                panel2 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                passCom = new javax.swing.JPasswordField();
                passCur = new javax.swing.JPasswordField();
                passAft = new javax.swing.JPasswordField();
                jButton2 = new javax.swing.JButton();
                passCurEr = new javax.swing.JLabel();
                passAftEr = new javax.swing.JLabel();
                passComEr = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jPanel3.setBackground(new java.awt.Color(255, 255, 255));

                jPanel1.setBackground(new java.awt.Color(23, 87, 183));

                jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("THAY ĐỔI THÔNG TIN");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(66, 66, 66)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(24, 24, 24)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(27, Short.MAX_VALUE)));

                panel.setBackground(new java.awt.Color(255, 255, 255));

                jLabel2.setText("Họ và tên");

                jLabel3.setText("Email");

                jButton1.setBackground(new java.awt.Color(23, 87, 183));
                jButton1.setFont(new java.awt.Font("SF Pro Display", 0, 16)); // NOI18N
                jButton1.setText("Lưu thay đổi");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel7.setText("Mật khẩu");

                javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
                panel.setLayout(panelLayout);
                panelLayout.setHorizontalGroup(
                                panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelLayout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addGroup(panelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jButton1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                158,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(panelLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addComponent(jLabel2)
                                                                                                .addComponent(tenTaiKhoan,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                336,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(password)
                                                                                                .addComponent(email)
                                                                                                .addComponent(jLabel3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                39,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel7)))
                                                                .addContainerGap(34, Short.MAX_VALUE)));
                panelLayout.setVerticalGroup(
                                panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelLayout.createSequentialGroup()
                                                                .addGap(33, 33, 33)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(tenTaiKhoan,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(email,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel7)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(password,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                45,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                35,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                43,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                jTabbedPane1.addTab("Thông tin", panel);

                panel2.setBackground(new java.awt.Color(255, 255, 255));

                jLabel4.setText("Mật khẩu hiện tại ");

                jLabel5.setText("Mật khẩu mới");

                jLabel6.setText("Nhập lại mật khẩu mới");

                jButton2.setBackground(new java.awt.Color(23, 87, 183));
                jButton2.setText("Đổi mật khẩu");
                jButton2.setMaximumSize(new java.awt.Dimension(119, 29));
                jButton2.setMinimumSize(new java.awt.Dimension(119, 29));
                jButton2.setPreferredSize(new java.awt.Dimension(119, 29));
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                passCurEr.setForeground(new java.awt.Color(255, 51, 102));

                passAftEr.setForeground(new java.awt.Color(255, 51, 102));

                passComEr.setForeground(new java.awt.Color(255, 51, 102));

                javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
                panel2.setLayout(panel2Layout);
                panel2Layout.setHorizontalGroup(
                                panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panel2Layout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addGroup(panel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jButton2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                158,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(panel2Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addComponent(jLabel6)
                                                                                                .addComponent(jLabel5)
                                                                                                .addComponent(jLabel4)
                                                                                                .addComponent(passCom,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                321,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(passAft)
                                                                                                .addComponent(passCur)
                                                                                                .addComponent(passCurEr,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(passAftEr,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(passComEr,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)))
                                                                .addContainerGap(49, Short.MAX_VALUE)));
                panel2Layout.setVerticalGroup(
                                panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panel2Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passCur,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(2, 2, 2)
                                                                .addComponent(passCurEr)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passAft,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passAftEr)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel6)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passCom,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                41,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(passComEr)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                64,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                43,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap()));

                jTabbedPane1.addTab("Mật khẩu", panel2);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(5, 5, 5)
                                                                .addComponent(jTabbedPane1)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
                boolean check = true;
                String curPass = passCur.getText();
                String newPass = passAft.getText();
                String newPassConf = passCom.getText();

                if (curPass.length() == 0) {
                        check = false;
                        passCurEr.setText("Vui lòng nhập mật khẩu hiện tại");
                } else {
                        passCurEr.setText("");
                }
                if (newPass.length() == 0) {
                        check = false;
                        passAftEr.setText("Vui lòng nhập mật khẩu mới");
                } else {
                        passAftEr.setText("");
                }
                if (newPassConf.length() == 0) {
                        check = false;
                        passComEr.setText("Vui lòng xác nhận lại mật khẩu");
                } else {
                        passComEr.setText("");
                }
                if (check == true) {
                        if (BCrypt.checkpw(curPass, accCur.getMatKhau())) {
//                                 BCrypt.hashpw(txtpassword.getText(), BCrypt.gensalt(12))
                                if (newPass.length() < 6) {
                                        JOptionPane.showMessageDialog(this,
                                                        "Vui lòng nhập mật khẩu mới lớn bằng 6 kí tự");
                                } else {
                                        if (newPass.equals(newPassConf)) {
                                                String pass = BCrypt.hashpw(passAft.getText(), BCrypt.gensalt(12));
                                                accCur.setMatKhau(pass);
                                                NguoiDungDao.getInstance().update(accCur);
                                                JOptionPane.showMessageDialog(this, "Thay đổi mật khẩu thành công!");
                                        } else {
                                                JOptionPane.showMessageDialog(this, "Mật khẩu mới không khớp");
                                        }
                                }
                        } else {
                                JOptionPane.showMessageDialog(this, "Mật khẩu hiện tại không đúng ");
                                passCur.setText("");
                        }
                }
        }// GEN-LAST:event_jButton2ActionPerformed

        static boolean isValid(String email) {
                String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
                return email.matches(regex);
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
                String nameAccount = tenTaiKhoan.getText();
                String emailAccount = email.getText();
                String passwordAccount = password.getText();
                if (nameAccount.equals("") || emailAccount.equals("") || passwordAccount.equals("")) {
                        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !");
                } else {
                        if (isValid(emailAccount)) {
                                if (BCrypt.checkpw(passwordAccount, accCur.getMatKhau())) {
                                        accCur.setHoTen(nameAccount);
                                        accCur.setEmail(emailAccount);
                                        NguoiDungDao.getInstance().update(accCur);
                                        JOptionPane.showMessageDialog(this, "Đã thay đổi thành công !");
                                } else {
                                        JOptionPane.showMessageDialog(this, "Sai mật khẩu !");
                                }
                        } else {
                                JOptionPane.showMessageDialog(this, "Email không đúng định dạng !");
                        }
                }
        }// GEN-LAST:event_jButton1ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ChangeMatKhau.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ChangeMatKhau.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ChangeMatKhau.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ChangeMatKhau.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }
                // </editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                ChangeMatKhau dialog = new ChangeMatKhau(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField email;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JPanel panel;
        private javax.swing.JPanel panel2;
        private javax.swing.JPasswordField passAft;
        private javax.swing.JLabel passAftEr;
        private javax.swing.JPasswordField passCom;
        private javax.swing.JLabel passComEr;
        private javax.swing.JPasswordField passCur;
        private javax.swing.JLabel passCurEr;
        private javax.swing.JPasswordField password;
        private javax.swing.JTextField tenTaiKhoan;
        // End of variables declaration//GEN-END:variables
}
