/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.ConvertDate;
import Controller.PDFController;
import Controller.SanPhamDBController;
import Controller.SearchKhachHang;
import Controller.SearchLoHang;
import Controller.UserController;
import Dao.LoHangDao;
import Model.BanHang;
import Model.ChiTietBanHang;
import Model.KhachHang;
import Model.LoHang;
import Model.SanPham;
import com.formdev.flatlaf.json.ParseException;
import java.awt.HeadlessException;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TieuSoi
 */
public class FormBanHang extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormBanHang
     */
    private DefaultTableModel tblModel;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    private ArrayList<LoHang> allProduct;
    private String MaPhieu;
    private ArrayList<ChiTietBanHang> CTPhieu;
    KhachHang khachHang;

    public FormBanHang() {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        txtNguoiTao.setText(UserController.getInstance().getHoTen());
        initTable();
        tblSanPham.setDefaultEditor(Object.class, null);
        tblNhapHang.setDefaultEditor(Object.class, null);
        allProduct = LoHangDao.getInstance().selectAll();
        loadDataToTableProduct(allProduct);
        txtNguoiTao.setFocusable(false);

    }

    public final void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{"Mã SP", "Tên SP", "Số lượng", "Đơn giá"};
        tblModel.setColumnIdentifiers(headerTbl);
        tblSanPham.setModel(tblModel);
        tblSanPham.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblSanPham.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblSanPham.getColumnModel().getColumn(2).setPreferredWidth(5);
        tblNhapHang.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblNhapHang.getColumnModel().getColumn(1).setPreferredWidth(10);
        tblNhapHang.getColumnModel().getColumn(2).setPreferredWidth(250);
    }

    private void loadDataToTableProduct(ArrayList<LoHang> arrProd) {
        try {
            tblModel.setRowCount(0);
            for (var i : arrProd) {
                tblModel.addRow(new Object[]{
                    i.getMaLoHangCode(), i.getTenSanPham(), i.getSoLuong(), formatter.format(i.getGiaBan()) + "đ"
                });
            }
        } catch (Exception e) {
        }
    }

    public double tinhTongTien() {
        double tt = 0;
        for (var i : CTPhieu) {
            tt += (i.getTongTien());
        }
        return tt;
    }

    public void loadDataToTableNhapHang() {
        double sum = 0;
        try {
            DefaultTableModel tblNhapHangmd = (DefaultTableModel) tblNhapHang.getModel();
            tblNhapHangmd.setRowCount(0);

            for (int i = 0; i < CTPhieu.size(); i++) {
                tblNhapHangmd.addRow(new Object[]{
                    i + 1, CTPhieu.get(i).getMaLoHangCode(), CTPhieu.get(i).getTenSanPham(),
                    CTPhieu.get(i).getSoLuong(), formatter.format(CTPhieu.get(i).getTongTien()) + "đ"
                });
                sum += CTPhieu.get(i).getTongTien();
            }
        } catch (Exception e) {
        }
        textTongTien.setText(formatter.format(sum) + "đ");
    }

    public void setNguoiTao(String name) {
        txtNguoiTao.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNguoiTao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhapHang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        textTongTien = new javax.swing.JLabel();
        deleteProduct = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtMaPhieu1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtKhachHang = new javax.swing.JTextField();
        btnReset1 = new javax.swing.JButton();
        lbKhachHang = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThemKH = new javax.swing.JButton();
        btnNhapHang2 = new javax.swing.JButton();
        btnNhapHang3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        addProduct = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnVanPhongPham = new javax.swing.JButton();
        btnSach = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Người tạo phiếu");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtNguoiTao.setEditable(false);
        txtNguoiTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNguoiTaoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNguoiTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, 36));

        tblNhapHang.setFont(tblNhapHang.getFont().deriveFont((float) 15));
        tblNhapHang.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "STT", "Mã SP", "Tên SP", "Số lượng", "Đơn giá"
                }));
        jScrollPane1.setViewportView(tblNhapHang);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 580, 440));

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel5.setText("Tổng tiền:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 690, 130, 30));

        textTongTien.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        textTongTien.setForeground(new java.awt.Color(255, 0, 0));
        textTongTien.setText("0đ");
        jPanel2.add(textTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 690, -1, 30));

        deleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/error_icon_24.png"))); // NOI18N
        deleteProduct.setText("Xoá sản phẩm");
        deleteProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductActionPerformed(evt);
            }
        });
        jPanel2.add(deleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 140, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/write_icon_24.png"))); // NOI18N
        jButton1.setText("Sửa số lượng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, -1, 40));

        txtMaPhieu1.setEditable(false);
        txtMaPhieu1.setEnabled(false);
        txtMaPhieu1.setFocusable(false);
        jPanel2.add(txtMaPhieu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 210, 36));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        txtKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKhachHangKeyReleased(evt);
            }
        });

        btnReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_refesh.png"))); // NOI18N
        btnReset1.setText("Xác nhận");
        btnReset1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        lbKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbKhachHang.setText("Thông Tin Khách Hàng");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 196,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnReset1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(lbKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lbKhachHang)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 350, 130));

        jLabel2.setText("Mã phiếu nhập");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnThemKH.setBackground(new java.awt.Color(0, 153, 51));
        btnThemKH.setForeground(new java.awt.Color(255, 255, 255));
        btnThemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/add_icon_24.png"))); // NOI18N
        btnThemKH.setBorder(null);
        btnThemKH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemKH.setLabel("Thêm KH");
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });
        jPanel2.add(btnThemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 110, 40));

        btnNhapHang2.setBackground(new java.awt.Color(23, 87, 183));
        btnNhapHang2.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapHang2.setText("Xuất hàng");
        btnNhapHang2.setBorder(null);
        btnNhapHang2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapHang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHang2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhapHang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 690, 123, 37));

        btnNhapHang3.setBackground(new java.awt.Color(204, 0, 0));
        btnNhapHang3.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapHang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_refesh.png"))); // NOI18N
        btnNhapHang3.setText("Reset Hóa Đơn");
        btnNhapHang3.setBorder(null);
        btnNhapHang3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapHang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHang3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhapHang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 120, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 620, 750));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblSanPham.setFont(tblSanPham.getFont().deriveFont((float) 15));
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Mã máy", "Tên máy", "Số lượng", "Đơn giá"
                }));
        jScrollPane2.setViewportView(tblSanPham);

        jLabel4.setText("Số lượng");

        txtSoLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoLuong.setText("1");
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        addProduct.setBackground(new java.awt.Color(23, 87, 183));
        addProduct.setForeground(new java.awt.Color(255, 255, 255));
        addProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/add_icon_24.png"))); // NOI18N
        addProduct.setText("Thêm");
        addProduct.setBorder(null);
        addProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_refesh.png"))); // NOI18N
        btnReset.setText("Làm mới");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnVanPhongPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_refesh.png"))); // NOI18N
        btnVanPhongPham.setText("Văn Phòng Phẩm");
        btnVanPhongPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVanPhongPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVanPhongPhamActionPerformed(evt);
            }
        });

        btnSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_refesh.png"))); // NOI18N
        btnSach.setText("Sách");
        btnSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(17, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(btnSach, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnVanPhongPham, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 352,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 129,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnVanPhongPham, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSach, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(13, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout
                                                .createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 65,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 522,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNguoiTaoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNguoiTaoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNguoiTaoActionPerformed

    private void deleteProductActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteProductActionPerformed
        // TODO add your handling code here:
        int i_row = tblNhapHang.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm để xoá khỏi bảng bán hàng !");
        } else {
            CTPhieu.remove(i_row);
            loadDataToTableNhapHang();
            textTongTien.setText(formatter.format(tinhTongTien()) + "đ");
        }
    }// GEN-LAST:event_deleteProductActionPerformed

    public LoHang findLoHang(String masp) {
        for (var i : allProduct) {
            if (masp.equals(i.getMaLoHangCode())) {
                return i;
            }
        }
        return null;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i_row = tblNhapHang.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm để xoá sửa số lượng !");
        } else {
            String newSL = JOptionPane.showInputDialog(this, "Nhập số lượng cần thay đổi", "Thay đổi số lượng",
                    QUESTION_MESSAGE);
            if (newSL != null) {
                int soLuong;
                try {
                    soLuong = Integer.parseInt(newSL);
                    if (soLuong > 0) {
                        if (soLuong > findLoHang(CTPhieu.get(i_row).getMaLoHangCode()).getSoLuong()) {
                            JOptionPane.showMessageDialog(this, "Số lượng không đủ !");
                        } else {
                            CTPhieu.get(i_row).setSoLuong(soLuong);
                            CTPhieu.get(i_row).setTongTien(
                                    soLuong * findLoHang(CTPhieu.get(i_row).getMaLoHangCode()).getGiaBan());
                            loadDataToTableNhapHang();
                            textTongTien.setText(formatter.format(tinhTongTien()) + "đ");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng lớn hơn 0");

                    }
                } catch (HeadlessException | NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng ở dạng số nguyên!");
                }
            }
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtSoLuongActionPerformed

    public ChiTietBanHang findCTPhieu(String maSp) {
        if (CTPhieu != null) {
            for (var i : CTPhieu) {
                if (maSp.equals(i.getMaLoHangCode())) {
                    return i;
                }
            }
        }
        return null;
    }

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addProductActionPerformed
        // TODO add your handling code here:
        if (CTPhieu == null) {
            CTPhieu = new ArrayList<ChiTietBanHang>();
        }
        int i_row = tblSanPham.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm để xuất hàng !");
            return;
        }

        String maLoHangCode = tblSanPham.getValueAt(i_row, 0).toString();

        LoHang selectedProduct = SearchLoHang.getInstance().searchByMaLoHangCodeItem(maLoHangCode);
        int availableQuantity = selectedProduct.getSoLuong();
        if (availableQuantity == 0) {
            JOptionPane.showMessageDialog(this, "Sản phẩm đã hết hàng !");
            return;
        }

        int enteredQuantity;
        try {
            enteredQuantity = Integer.parseInt(txtSoLuong.getText().trim());
            if (enteredQuantity <= 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng lớn hơn 0");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng ở dạng số nguyên!");
            return;
        }

        if (enteredQuantity > availableQuantity) {
            JOptionPane.showMessageDialog(this, "Số lượng không đủ !");
            return;
        }

        ChiTietBanHang existingProduct = findCTPhieu(selectedProduct.getMaLoHangCode());
        if (existingProduct != null) {
            if (existingProduct.getSoLuong() + enteredQuantity > availableQuantity) {
                JOptionPane.showMessageDialog(this, "Số lượng không đủ !");
                return;
            } else {
                existingProduct.setSoLuong(existingProduct.getSoLuong() + enteredQuantity);
                existingProduct.setTongTien(existingProduct.getSoLuong() * selectedProduct.getGiaBan());
            }
        } else {
            ChiTietBanHang newOrderDetail = new ChiTietBanHang(MaPhieu, selectedProduct.getMaLoHangCode(),
                    selectedProduct.getTenSanPham(), enteredQuantity, selectedProduct.getGiaBan() * enteredQuantity);
            newOrderDetail.setMaLoHang(selectedProduct.getMaLoHang());
            CTPhieu.add(newOrderDetail);
        }

        loadDataToTableNhapHang();
    }// GEN-LAST:event_addProductActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String textSearch = txtSearch.getText().toLowerCase().trim();
        ArrayList<LoHang> lstSearch = SearchLoHang.getInstance().searchTatCaLoHang(textSearch);
        loadDataToTableProduct(lstSearch);

    }// GEN-LAST:event_txtSearchKeyReleased

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        allProduct = LoHangDao.getInstance().selectAll();
        loadDataToTableProduct(allProduct);
    }// GEN-LAST:event_btnResetActionPerformed

    private void txtKhachHangKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtKhachHangKeyReleased
        // TODO add your handling code here:
    }// GEN-LAST:event_txtKhachHangKeyReleased

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
        String textSdtKhacHang = txtKhachHang.getText().toLowerCase().trim();
        khachHang = SearchKhachHang.getInstance().getKHBySdt(textSdtKhacHang);
        if (khachHang == null) {
            lbKhachHang.setText("Không tìm thấy khách hàng!");
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng trong danh sách vui lòng thêm mới!",
                    "Cảnh báo", JOptionPane.WARNING_MESSAGE);

        } else {
            lbKhachHang.setText(khachHang.getHoTenKH() + " - " + khachHang.getSdt());
        }
    }// GEN-LAST:event_btnReset1ActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemKHActionPerformed
        // TODO add your handling code here:
        AddKhachHangBanHang a = new AddKhachHangBanHang(this,
                (JFrame) javax.swing.SwingUtilities.getWindowAncestor(this), rootPaneCheckingEnabled);
        a.setVisible(true);
    }// GEN-LAST:event_btnThemKHActionPerformed

    private void btnNhapHang2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNhapHang2ActionPerformed
        // TODO add your handling code here:

        if (khachHang != null && CTPhieu != null && !CTPhieu.isEmpty()) {
            int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xuất hàng ?", "Xác nhận xuất hàng",
                    JOptionPane.YES_NO_OPTION);
            Date ngayLap = new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String formattedDate = dateFormat.format(ngayLap);
            System.err.println(formattedDate);

            ConvertDate converter = ConvertDate.getInstance();

            SanPhamDBController sanPhamDBController = new SanPhamDBController();
            BanHang banHang = sanPhamDBController.insertBanHang(UserController.getInstance().getMaNguoiDung(),
                    khachHang.getMaKH(), formattedDate, CTPhieu);
            JOptionPane.showMessageDialog(this, "Xuất hàng thành công !");
            int res = JOptionPane.showConfirmDialog(this, "Bạn có muốn xuất file pdf ?");
            if (res == JOptionPane.YES_OPTION) {
                PDFController writepdf = new PDFController();
                writepdf.writePhieuXuat(banHang);
            }

            khachHang = null;
            lbKhachHang.setText("Thông tin khách hàng");
            allProduct = LoHangDao.getInstance().selectAll();
            loadDataToTableProduct(allProduct);
            CTPhieu.clear();
            loadDataToTableNhapHang();
        } else {
            JOptionPane.showConfirmDialog(this, "Vui lòng điền đầy đủ thông tin?", "Cảnh báo",
                    JOptionPane.YES_NO_OPTION);
        }
    }// GEN-LAST:event_btnNhapHang2ActionPerformed

    private void btnNhapHang3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNhapHang3ActionPerformed
        // TODO add your handling code here:
        if (CTPhieu != null && !CTPhieu.isEmpty()) {
            int confirmed = JOptionPane.showConfirmDialog(null,
                    "Bạn có chắc chắn muốn reset hóa đơn?", "Xác nhận",
                    JOptionPane.YES_NO_OPTION);
            // Nếu người dùng chọn YES, tiến hành reset hóa đơn
            if (confirmed == JOptionPane.YES_OPTION) {
                CTPhieu.clear();
                loadDataToTableNhapHang();
            }
        }
    }// GEN-LAST:event_btnNhapHang3ActionPerformed

    private void btnVanPhongPhamActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVanPhongPhamActionPerformed
        // TODO add your handling code here:
        ArrayList<LoHang> lstVanPhongPham = SearchLoHang.getInstance().lstDanhSachVanPhongPham();
        loadDataToTableProduct(lstVanPhongPham);

    }// GEN-LAST:event_btnVanPhongPhamActionPerformed

    private void btnSachActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSachActionPerformed
        // TODO add your handling code here:
        ArrayList<LoHang> lstSach = SearchLoHang.getInstance().lsDanhSachSach();
        loadDataToTableProduct(lstSach);
    }// GEN-LAST:event_btnSachActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JButton btnNhapHang2;
    private javax.swing.JButton btnNhapHang3;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnSach;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnVanPhongPham;
    private javax.swing.JButton deleteProduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbKhachHang;
    private javax.swing.JTable tblNhapHang;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JLabel textTongTien;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JTextField txtMaPhieu1;
    private javax.swing.JTextField txtNguoiTao;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables
}
