/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.UserController;
import Dao.NguoiDungDao;
import Model.NguoiDung;
import java.awt.Color;
import javax.swing.UIManager;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author TieuSoi
 */
public class GUIAdmin extends javax.swing.JFrame {

    Color DefaultColor, ClickedColor;

    /**
     * Creates new form GUIAdmin
     */
    public GUIAdmin() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

    }

    public GUIAdmin(String a) throws UnsupportedLookAndFeelException {

        DefaultColor = new Color(23, 87, 183);
        ClickedColor = new Color(63, 160, 231);

        UIManager.setLookAndFeel(new FlatLightLaf());
        UIManager.put("Table.showVerticalLines", true);
        UIManager.put("Table.showHorizontalLines", true);

        setLocationRelativeTo(null);

        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        FormSanPham pf = new FormSanPham();
        MainContent.add(pf).setVisible(true);
        initColorNavbar("SanPham");
        initUser(NguoiDungDao.getInstance().selectById(a));
        NameUser.setText(UserController.getInstance().getHoTen());

    }

    void initUser(NguoiDung acc) {
        UserController userController = UserController.getInstance();
        userController.setMaNguoiDung(acc.getMaNguoiDung());
        userController.setMaNguoiDungCode(acc.getMaNguoiDungCode());
        userController.setTenDangNhap(acc.getTenDangNhap());
        userController.setMatKhau(acc.getMatKhau());
        userController.setHoTen(acc.getHoTen());
        userController.setEmail(acc.getEmail());
        userController.setQuyen(acc.getQuyen());
    }

    void initColorNavbar(String keyword) {
        // Reset all buttons to default color
        SanPham.setBackground(DefaultColor);
        PhieuNhap.setBackground(DefaultColor);
        NhapHang.setBackground(DefaultColor);
        XuatHang.setBackground(DefaultColor);
        PhieuXuat.setBackground(DefaultColor);
        NhaCungCap.setBackground(DefaultColor);
        TonKho.setBackground(DefaultColor);
        TaiKhoan1.setBackground(DefaultColor);
        KHACHHANG.setBackground(DefaultColor);
        ThongKe1.setBackground(DefaultColor);

        // Set clicked color for the button corresponding to the keyword
        switch (keyword) {
            case "SanPham":
                SanPham.setBackground(ClickedColor);
                break;
            case "PhieuNhap":
                PhieuNhap.setBackground(ClickedColor);
                break;
            case "NhapHang":
                NhapHang.setBackground(ClickedColor);
                break;
            case "XuatHang":
                XuatHang.setBackground(ClickedColor);
                break;
            case "PhieuXuat":
                PhieuXuat.setBackground(ClickedColor);
                break;
                
            case "NhaCungCap":
                NhaCungCap.setBackground(ClickedColor);
                break;
            case "TonKho":
                TonKho.setBackground(ClickedColor);
                break;
            case "TaiKhoan1":
                TaiKhoan1.setBackground(ClickedColor);
                break;
            case "KhachHang":
                KHACHHANG.setBackground(ClickedColor);
                break;
            case "ThongKe":
                ThongKe1.setBackground(ClickedColor);
                break;
            default:
                break;
        }
    }

    void showForm(JInternalFrame jfrom) {
        MainContent.removeAll();
        MainContent.add(jfrom).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavbarMenu = new javax.swing.JPanel();
        SanPham = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NhapHang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PhieuNhap = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        XuatHang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        NhaCungCap = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NameUser = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PhieuXuat = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TonKho = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TaiKhoan1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Account = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ThongKe1 = new javax.swing.JPanel();
        THONGKE = new javax.swing.JLabel();
        KHACHHANG = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        MainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavbarMenu.setBackground(new java.awt.Color(23, 87, 183));
        NavbarMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SanPham.setBackground(new java.awt.Color(23, 87, 183));
        SanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SanPhamMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                SanPhamMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_product.png"))); // NOI18N
        jLabel1.setText("SẢN PHẨM");

        javax.swing.GroupLayout SanPhamLayout = new javax.swing.GroupLayout(SanPham);
        SanPham.setLayout(SanPhamLayout);
        SanPhamLayout.setHorizontalGroup(
                SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SanPhamLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)
                                .addContainerGap(82, Short.MAX_VALUE)));
        SanPhamLayout.setVerticalGroup(
                SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SanPhamLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addContainerGap()));

        NavbarMenu.add(SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 40));

        NhapHang.setBackground(new java.awt.Color(23, 87, 183));
        NhapHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhapHangMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhapHangMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_nhap_hang.png"))); // NOI18N
        jLabel2.setText("NHẬP HÀNG");

        javax.swing.GroupLayout NhapHangLayout = new javax.swing.GroupLayout(NhapHang);
        NhapHang.setLayout(NhapHangLayout);
        NhapHangLayout.setHorizontalGroup(
                NhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NhapHangLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)
                                .addContainerGap(74, Short.MAX_VALUE)));
        NhapHangLayout.setVerticalGroup(
                NhapHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NhapHangLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        NavbarMenu.add(NhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, -1));

        PhieuNhap.setBackground(new java.awt.Color(23, 87, 183));
        PhieuNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhieuNhapMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                PhieuNhapMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/add_icon_24.png"))); // NOI18N
        jLabel3.setText("PHIẾU NHẬP");

        javax.swing.GroupLayout PhieuNhapLayout = new javax.swing.GroupLayout(PhieuNhap);
        PhieuNhap.setLayout(PhieuNhapLayout);
        PhieuNhapLayout.setHorizontalGroup(
                PhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PhieuNhapLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)
                                .addContainerGap(71, Short.MAX_VALUE)));
        PhieuNhapLayout.setVerticalGroup(
                PhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PhieuNhapLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addContainerGap()));

        NavbarMenu.add(PhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 40));

        XuatHang.setBackground(new java.awt.Color(23, 87, 183));
        XuatHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XuatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XuatHangMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                XuatHangMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_ban_hang.png"))); // NOI18N
        jLabel4.setText("BÁN HÀNG");

        javax.swing.GroupLayout XuatHangLayout = new javax.swing.GroupLayout(XuatHang);
        XuatHang.setLayout(XuatHangLayout);
        XuatHangLayout.setHorizontalGroup(
                XuatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(XuatHangLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4)
                                .addContainerGap(86, Short.MAX_VALUE)));
        XuatHangLayout.setVerticalGroup(
                XuatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, XuatHangLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addContainerGap()));

        NavbarMenu.add(XuatHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 40));

        DangXuat.setBackground(new java.awt.Color(23, 87, 183));
        DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DangXuatMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                DangXuatMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logout.png"))); // NOI18N
        jLabel5.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
                DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DangXuatLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5)
                                .addContainerGap(76, Short.MAX_VALUE)));
        DangXuatLayout.setVerticalGroup(
                DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DangXuatLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        NavbarMenu.add(DangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 240, -1));

        NhaCungCap.setBackground(new java.awt.Color(23, 87, 183));
        NhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhaCungCapMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhaCungCapMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_suplier.png"))); // NOI18N
        jLabel6.setText("NHÀ CUNG CẤP");

        javax.swing.GroupLayout NhaCungCapLayout = new javax.swing.GroupLayout(NhaCungCap);
        NhaCungCap.setLayout(NhaCungCapLayout);
        NhaCungCapLayout.setHorizontalGroup(
                NhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NhaCungCapLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)
                                .addContainerGap(41, Short.MAX_VALUE)));
        NhaCungCapLayout.setVerticalGroup(
                NhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhaCungCapLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addContainerGap()));

        NavbarMenu.add(NhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 40));

        NameUser.setBackground(new java.awt.Color(23, 87, 183));
        NameUser.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        NameUser.setForeground(new java.awt.Color(255, 255, 255));
        NameUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameUser.setText("ADMIN");
        NameUser.setToolTipText("");
        NavbarMenu.add(NameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, -1));

        jLabel8.setBackground(new java.awt.Color(23, 87, 183));
        jLabel8.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/bookstoreiconpng60.png"))); // NOI18N
        jLabel8.setText("Tên nhà sách");
        NavbarMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 70));

        PhieuXuat.setBackground(new java.awt.Color(23, 87, 183));
        PhieuXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PhieuXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhieuXuatMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                PhieuXuatMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/add_icon_24.png"))); // NOI18N
        jLabel9.setText("PHIẾU XUẤT");

        javax.swing.GroupLayout PhieuXuatLayout = new javax.swing.GroupLayout(PhieuXuat);
        PhieuXuat.setLayout(PhieuXuatLayout);
        PhieuXuatLayout.setHorizontalGroup(
                PhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PhieuXuatLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9)
                                .addContainerGap(74, Short.MAX_VALUE)));
        PhieuXuatLayout.setVerticalGroup(
                PhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PhieuXuatLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        NavbarMenu.add(PhieuXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 40));

        TonKho.setBackground(new java.awt.Color(23, 87, 183));
        TonKho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TonKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TonKhoMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                TonKhoMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/add_icon_24.png"))); // NOI18N
        jLabel10.setText("TỒN KHO");

        javax.swing.GroupLayout TonKhoLayout = new javax.swing.GroupLayout(TonKho);
        TonKho.setLayout(TonKhoLayout);
        TonKhoLayout.setHorizontalGroup(
                TonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TonKhoLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(60, Short.MAX_VALUE)));
        TonKhoLayout.setVerticalGroup(
                TonKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TonKhoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        NavbarMenu.add(TonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 240, -1));

        TaiKhoan1.setBackground(new java.awt.Color(23, 87, 183));
        TaiKhoan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TaiKhoan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaiKhoan1MouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                TaiKhoan1MousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icon_account.png"))); // NOI18N
        jLabel12.setText("TÀI KHOẢN");

        javax.swing.GroupLayout TaiKhoan1Layout = new javax.swing.GroupLayout(TaiKhoan1);
        TaiKhoan1.setLayout(TaiKhoan1Layout);
        TaiKhoan1Layout.setHorizontalGroup(
                TaiKhoan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TaiKhoan1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel12)
                                .addContainerGap(82, Short.MAX_VALUE)));
        TaiKhoan1Layout.setVerticalGroup(
                TaiKhoan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TaiKhoan1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        NavbarMenu.add(TaiKhoan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 240, -1));

        Account.setBackground(new java.awt.Color(23, 87, 183));
        Account.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                AccountMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/info_icon_24.png"))); // NOI18N
        jLabel14.setText("ĐỔI THÔNG TIN");

        javax.swing.GroupLayout AccountLayout = new javax.swing.GroupLayout(Account);
        Account.setLayout(AccountLayout);
        AccountLayout.setHorizontalGroup(
                AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AccountLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 176,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(34, Short.MAX_VALUE)));
        AccountLayout.setVerticalGroup(
                AccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AccountLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        NavbarMenu.add(Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 240, -1));

        ThongKe1.setBackground(new java.awt.Color(23, 87, 183));
        ThongKe1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongKe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKe1MouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThongKe1MousePressed(evt);
            }
        });

        THONGKE.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        THONGKE.setForeground(new java.awt.Color(255, 255, 255));
        THONGKE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/char_icon_24.png"))); // NOI18N
        THONGKE.setText("THỐNG KÊ");

        javax.swing.GroupLayout ThongKe1Layout = new javax.swing.GroupLayout(ThongKe1);
        ThongKe1.setLayout(ThongKe1Layout);
        ThongKe1Layout.setHorizontalGroup(
                ThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ThongKe1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(THONGKE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        ThongKe1Layout.setVerticalGroup(
                ThongKe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ThongKe1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(THONGKE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        THONGKE.getAccessibleContext().setAccessibleParent(THONGKE);

        NavbarMenu.add(ThongKe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 240, 50));

        KHACHHANG.setBackground(new java.awt.Color(23, 87, 183));
        KHACHHANG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        KHACHHANG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KHACHHANGMouseClicked(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                KHACHHANGMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/char_icon_24.png"))); // NOI18N
        jLabel13.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout KHACHHANGLayout = new javax.swing.GroupLayout(KHACHHANG);
        KHACHHANG.setLayout(KHACHHANGLayout);
        KHACHHANGLayout.setHorizontalGroup(
                KHACHHANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KHACHHANGLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13)
                                .addContainerGap(59, Short.MAX_VALUE)));
        KHACHHANGLayout.setVerticalGroup(
                KHACHHANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(KHACHHANGLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        NavbarMenu.add(KHACHHANG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 240, -1));

        MainContent.setBackground(new java.awt.Color(255, 255, 255));
        MainContent.setPreferredSize(new java.awt.Dimension(1200, 750));

        javax.swing.GroupLayout MainContentLayout = new javax.swing.GroupLayout(MainContent);
        MainContent.setLayout(MainContentLayout);
        MainContentLayout.setHorizontalGroup(
                MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1189, Short.MAX_VALUE));
        MainContentLayout.setVerticalGroup(
                MainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 750, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NavbarMenu, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MainContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1189, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NavbarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 750,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(MainContent, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SanPhamMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_SanPhamMouseClicked
        // TODO add your handling code here:
        showForm(new FormSanPham());
    }// GEN-LAST:event_SanPhamMouseClicked

    private void SanPhamMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_SanPhamMousePressed
        // TODO add your handling code here:
        initColorNavbar("SanPham");

    }// GEN-LAST:event_SanPhamMousePressed

    private void NhapHangMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NhapHangMouseClicked
        // TODO add your handling code here:
        FormNhapHang nhaphang = new FormNhapHang();
        MainContent.removeAll();
        MainContent.add(nhaphang).setVisible(true);
    }// GEN-LAST:event_NhapHangMouseClicked

    private void NhapHangMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NhapHangMousePressed
        // TODO add your handling code here:
        initColorNavbar("NhapHang");

    }// GEN-LAST:event_NhapHangMousePressed

    private void PhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PhieuNhapMouseClicked
        // TODO add your handling code here:
        showForm(new FormPhieuNhap());
    }// GEN-LAST:event_PhieuNhapMouseClicked

    private void PhieuNhapMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PhieuNhapMousePressed
        // TODO add your handling code here:
        initColorNavbar("PhieuNhap");

    }// GEN-LAST:event_PhieuNhapMousePressed

    private void XuatHangMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_XuatHangMouseClicked
        // TODO add your handling code here:
        showForm(new FormBanHang());
    }// GEN-LAST:event_XuatHangMouseClicked

    private void XuatHangMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_XuatHangMousePressed
        // TODO add your handling code here:
        initColorNavbar("XuatHang");
    }// GEN-LAST:event_XuatHangMousePressed

    private void DangXuatMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_DangXuatMouseClicked
        // TODO add your handling code here:
        int relly = JOptionPane.showConfirmDialog(
                null,
                "Bạn muốn thoát khỏi chương trình ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if (relly == JOptionPane.YES_OPTION) {
            this.dispose();
            FormLogin a = new FormLogin();
            a.setVisible(true);
        } else {
            DangXuat.setBackground(DefaultColor);
        }

    }// GEN-LAST:event_DangXuatMouseClicked

    private void DangXuatMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_DangXuatMousePressed
        // TODO add your handling code here:
    }// GEN-LAST:event_DangXuatMousePressed

    private void NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NhaCungCapMouseClicked
        // TODO add your handling code here:
        // FormNhaCungCap ncc = new FormNhaCungCap();
        // MainContent.removeAll();
        // MainContent.add(ncc).setVisible(true);\
        showForm(new FormNhaCungCap());
    }// GEN-LAST:event_NhaCungCapMouseClicked

    private void NhaCungCapMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_NhaCungCapMousePressed
        // TODO add your handling code here:
        initColorNavbar("NhaCungCap");

    }// GEN-LAST:event_NhaCungCapMousePressed

    private void PhieuXuatMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PhieuXuatMouseClicked
        // TODO add your handling code here:


        showForm(new FormPhieuXuat());
    }// GEN-LAST:event_PhieuXuatMouseClicked

    private void PhieuXuatMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PhieuXuatMousePressed
        // TODO add your handling code here:
        initColorNavbar("PhieuXuat");
    }// GEN-LAST:event_PhieuXuatMousePressed

    private void TonKhoMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TonKhoMouseClicked
        // TODO add your handling code here:
        showForm(new FormTonKho());
    }// GEN-LAST:event_TonKhoMouseClicked

    private void TonKhoMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TonKhoMousePressed
        // TODO add your handling code here:
        initColorNavbar("TonKho");

    }// GEN-LAST:event_TonKhoMousePressed

    private void TaiKhoan1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TaiKhoan1MouseClicked
        // TODO add your handling code here:
        showForm(new FormNguoiDung());
    }// GEN-LAST:event_TaiKhoan1MouseClicked

    private void TaiKhoan1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_TaiKhoan1MousePressed
        // TODO add your handling code here:
        initColorNavbar("TaiKhoan1");

    }// GEN-LAST:event_TaiKhoan1MousePressed

    private void KHACHHANGMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_KHACHHANGMouseClicked
        // TODO add your handling code here:
        showForm(new FormKhachHang());
    }// GEN-LAST:event_KHACHHANGMouseClicked

    private void KHACHHANGMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_KHACHHANGMousePressed
        // TODO add your handling code here:
        initColorNavbar("KhachHang");

    }// GEN-LAST:event_KHACHHANGMousePressed
    private NguoiDung getCurrentAcc()
    {
        NguoiDung nguoiDung = new NguoiDung();
        nguoiDung.setEmail(UserController.getInstance().getEmail());
        nguoiDung.setHoTen(UserController.getInstance().getHoTen());
        nguoiDung.setMaNguoiDung(UserController.getInstance().getMaNguoiDung());
        nguoiDung.setMaNguoiDungCode(UserController.getInstance().getMaNguoiDungCode());
        nguoiDung.setQuyen(UserController.getInstance().getQuyen());
        nguoiDung.setTenDangNhap(UserController.getInstance().getTenDangNhap());
        nguoiDung.setMatKhau(UserController.getInstance().getMatKhau());

        return nguoiDung;
    }
    private void AccountMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_AccountMouseClicked
        // TODO add your handling code here:
        ChangeMatKhau cp = new ChangeMatKhau(this, rootPaneCheckingEnabled, getCurrentAcc());
        cp.setVisible(true);

    }// GEN-LAST:event_AccountMouseClicked

    private void AccountMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_AccountMousePressed
        // TODO add your handling code here:
    }// GEN-LAST:event_AccountMousePressed

    private void ThongKe1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ThongKe1MouseClicked
        // TODO add your handling code here:
        showForm(new FromThongKe());
    }// GEN-LAST:event_ThongKe1MouseClicked

    private void ThongKe1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ThongKe1MousePressed
        // TODO add your handling code here:
        initColorNavbar("ThongKe");
    }// GEN-LAST:event_ThongKe1MousePressed

    /**
     * @param args the command line arguments
     */
//     public static void main(String args[]) throws UnsupportedLookAndFeelException
//     {
//     /* Create and display the form */
//     java.awt.EventQueue.invokeLater(new Runnable() {
//     public void run() {
//     new GUIAdmin().setVisible(true);
//     }
//     });
//     }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
                | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            try {
                new GUIAdmin("sa").setVisible(true); // Use the constructor with the int parameter
            } catch (UnsupportedLookAndFeelException e) {
                e.printStackTrace();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Account;
    private javax.swing.JPanel DangXuat;
    private javax.swing.JPanel KHACHHANG;
    private javax.swing.JPanel MainContent;
    private javax.swing.JLabel NameUser;
    private javax.swing.JPanel NavbarMenu;
    private javax.swing.JPanel NhaCungCap;
    private javax.swing.JPanel NhapHang;
    private javax.swing.JPanel PhieuNhap;
    private javax.swing.JPanel PhieuXuat;
    private javax.swing.JPanel SanPham;
    private javax.swing.JLabel THONGKE;
    private javax.swing.JPanel TaiKhoan1;
    private javax.swing.JPanel ThongKe1;
    private javax.swing.JPanel TonKho;
    private javax.swing.JPanel XuatHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
